apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: gpu-admission
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-admission
  template: 
    metadata:
      labels:
        app: gpu-admission
    spec:
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            weight: 1
      serviceAccount: gpu-admission
      containers:
      - image: bocloud-bj.io:5000/gpu-admission:1.1
        imagePullPolicy: IfNotPresent
        name: gpu-admission
        env:
        - name: LOG_LEVEL
          value: "1"
        ports:
        - containerPort: 3456
        resources:
          requests:
            memory: 64Mi
            cpu: 200m
          limits:
            memory: 128Mi
            cpu: 400m
      dnsPolicy: ClusterFirstWithHostNet
      priority: 2000000000
      hostNetwork: true
      priorityClassName: system-cluster-critical