apiVersion: v1
kind: Service
metadata:
  name: gpu-admission-svc
  namespace: kube-system
  labels:
    app: gpu-admission
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: 3456
  selector:
    app: gpu-admission
